import Head from "next/head";
import Link from "next/link";
import { Button } from "@/components/ui/Button";
import { trpc } from "@/lib/trpc";
import { LoadingCard } from "@/components/ui/LoadingSpinner";
import { ProjectCard } from "@/components/projects/ProjectCard";

export default function Home() {
  const { data: projectsData, isLoading } = trpc.projects.list.useQuery({ limit: 6 });

  return (
    <>
      <Head>
        <title>ArchitectureDeck — AI Architecture Designer</title>
        <meta name="description" content="Generate architecture diagrams and design documents with AI" />
      </Head>

      <div className="space-y-12">
        {/* Hero Section */}
        <section className="relative py-12 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-neon-cyan/5 via-transparent to-neon-magenta/5 rounded-3xl" />
          <div className="relative text-center max-w-3xl mx-auto px-4">
            <div className="inline-flex items-center gap-2 px-3 py-1 mb-6 bg-neon-cyan/10 border border-neon-cyan/30 rounded-full text-xs text-neon-cyan animate-fade-in">
              <span className="w-1.5 h-1.5 rounded-full bg-neon-cyan animate-pulse" />
              AI-Powered Architecture Design
            </div>
            
            <h1 className="text-4xl md:text-5xl font-display font-bold text-void-100 mb-4 animate-slide-up">
              Design Your{" "}
              <span className="text-gradient">Architecture</span>
              <br />
              in Minutes
            </h1>
            
            <p className="text-lg text-void-400 mb-8 animate-slide-up animate-delay-100">
              Describe your product or paste a GitHub URL. Get a complete architecture plan, 
              Mermaid diagrams, and a roadmap — all generated by AI.
            </p>

            <div className="flex flex-wrap justify-center gap-4 animate-slide-up animate-delay-200">
              <Link href="/projects/new">
                <Button variant="primary" size="lg">
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                  </svg>
                  Create New Design
                </Button>
              </Link>
              <Link href="/projects">
                <Button variant="secondary" size="lg">
                  View All Projects
                </Button>
              </Link>
            </div>
          </div>
        </section>

        {/* Features Grid */}
        <section className="grid md:grid-cols-3 gap-6">
          {features.map((feature, idx) => (
            <div
              key={feature.title}
              className="card p-6 animate-slide-up"
              style={{ animationDelay: `${(idx + 1) * 100}ms` }}
            >
              <div className={`w-12 h-12 rounded-xl ${feature.iconBg} flex items-center justify-center mb-4`}>
                {feature.icon}
              </div>
              <h3 className="text-lg font-semibold text-void-100 mb-2">{feature.title}</h3>
              <p className="text-sm text-void-400">{feature.description}</p>
            </div>
          ))}
        </section>

        {/* Recent Projects */}
        <section>
          <div className="flex items-center justify-between mb-6">
            <h2 className="section-title">Recent Projects</h2>
            <Link href="/projects" className="text-sm text-neon-cyan hover:text-neon-cyan/80 transition-colors">
              View all →
            </Link>
          </div>

          {isLoading ? (
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {[1, 2, 3].map((i) => (
                <LoadingCard key={i} />
              ))}
            </div>
          ) : projectsData?.items && projectsData.items.length > 0 ? (
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {projectsData.items.map((project) => (
                <ProjectCard key={project.id} project={project} />
              ))}
            </div>
          ) : (
            <div className="card p-12 text-center">
              <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-void-800 flex items-center justify-center">
                <svg className="w-8 h-8 text-void-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                </svg>
              </div>
              <h3 className="text-lg font-medium text-void-200 mb-2">No projects yet</h3>
              <p className="text-sm text-void-500 mb-6">Create your first project to get started</p>
              <Link href="/projects/new">
                <Button variant="primary">Create Project</Button>
              </Link>
            </div>
          )}
        </section>

        {/* How It Works */}
        <section className="py-8">
          <h2 className="section-title text-center mb-10">How It Works</h2>
          <div className="grid md:grid-cols-4 gap-6">
            {steps.map((step, idx) => (
              <div key={step.title} className="relative text-center">
                {idx < steps.length - 1 && (
                  <div className="hidden md:block absolute top-8 left-1/2 w-full h-0.5 bg-gradient-to-r from-neon-cyan/50 to-transparent" />
                )}
                <div className="relative inline-flex items-center justify-center w-16 h-16 mb-4 rounded-full bg-gradient-to-br from-neon-cyan/20 to-emerald-500/20 border border-neon-cyan/30">
                  <span className="text-xl font-bold text-neon-cyan">{idx + 1}</span>
                </div>
                <h3 className="font-semibold text-void-100 mb-2">{step.title}</h3>
                <p className="text-sm text-void-400">{step.description}</p>
              </div>
            ))}
          </div>
        </section>
      </div>
    </>
  );
}

const features = [
  {
    title: "AI-Generated Diagrams",
    description: "Get beautiful Mermaid diagrams automatically generated from your requirements.",
    icon: (
      <svg className="w-6 h-6 text-neon-cyan" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7m0 10a2 2 0 002 2h2a2 2 0 002-2V7a2 2 0 00-2-2h-2a2 2 0 00-2 2" />
      </svg>
    ),
    iconBg: "bg-neon-cyan/20 border border-neon-cyan/30",
  },
  {
    title: "Scale-Aware Design",
    description: "Choose your scale profile and get architecture recommendations tailored to your needs.",
    icon: (
      <svg className="w-6 h-6 text-neon-magenta" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
      </svg>
    ),
    iconBg: "bg-neon-magenta/20 border border-neon-magenta/30",
  },
  {
    title: "Version Control",
    description: "Track all iterations of your design with full version history and comparisons.",
    icon: (
      <svg className="w-6 h-6 text-neon-amber" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
    iconBg: "bg-neon-amber/20 border border-neon-amber/30",
  },
];

const steps = [
  {
    title: "Describe",
    description: "Write a prompt or paste a GitHub repo URL",
  },
  {
    title: "Configure",
    description: "Set constraints and scale profile",
  },
  {
    title: "Generate",
    description: "AI creates your architecture",
  },
  {
    title: "Review",
    description: "View diagrams and iterate",
  },
];
